version: "3"

services:
  redis:
    image: redis
    container_name: "laravel_redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:5.6
    container_name: "laravel_mysql"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"
    volumes:
      - db_data:/var/lib/mysql
      
  front:
    image: abiosoft/caddy
    container_name: "laravel_caddy"
    environment:
      - CADDYPATH=/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - ./docker/caddy/caddyssl:/etc/caddycerts
    depends_on:
      - app

  app:
    image: laravel_skeleton:build
    build: .
    container_name: "laravel_app"
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - redis
    command: /usr/local/sbin/php-fpm --allow-to-run-as-root

volumes:
  redis_data:
  db_data:  
